import Head from "next/head";
import { Heading, Section } from "../components/SectionElements";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <Heading>Auto Serwis</Heading>
      </Section>
    </div>
  );
}
